Iter9
zelas91/metric-collector pull request #17
Opened 2023-08-31 12:38 UTC by zelas91

2023-09-02 05:39 UTC, popoffvg requested changes

2023-09-02 05:39 UTC, popoffvg commented on internal/agent/client.go
> +		gzipBody, err := gzipCompress(body)
[minor]
Есть мидлвара, лучше этот код убрать

2023-09-02 05:39 UTC, popoffvg commented on internal/agent/client.go
> +			log.Debug("error compress body %v", err)
[major]

Нельзя игнорировать ошибку, т.к. возвращается `body = nil`. В случае возникновения ошибки будет очень сложно понять в чем проблема

2023-09-02 05:39 UTC, popoffvg commented on internal/server/repository/repository.go
> +	type memStorageAlias MemStorage
[major]

type definition здесь не нужен, поведение не расширяется

2023-09-02 05:39 UTC, popoffvg commented on internal/server/repository/repository.go
> +	mem := &struct {
[major]

В анонимной структуре дублируется поля storage. Она тут не нужна

2023-09-02 05:39 UTC, popoffvg commented on internal/server/repository/repository.go
> +func (m *MemStorage) UnmarshalJSON(bytes []byte) error {
[major]

Метод нигде не вызывается

2023-09-02 05:39 UTC, popoffvg commented on internal/server/service/service.go
> +				<-tickerStoreInterval.C
[minor]

Т.к. сделал gracefullshutdown, тут стоит его учитывать

2023-09-02 05:39 UTC, popoffvg commented on internal/server/service/service.go
> +					log.Debugf("save error %v", err)
[major]

Ошибку нужно записывать с уровнем error

2023-09-02 13:35 UTC, zelas91 commented
golang как посмотреть откуда вызвался метод?

2023-09-05 07:04 UTC, zelas91 commented
iter 9 done

2023-09-05 07:10 UTC, merged